language: node_js
node_js:
  - "lts/*"

install:
  - npm install # make sure to install the deps when Travis runs.
after_success:
  - npm run lh -- --perf=75 --seo=75 --a11y=75 --bp=75 https://blog-staging.vatz88.in/
