language: node_js
node_js:
  - "lts/*"

install:
  - npm install # make sure to install the deps when Travis runs.
after_success:
  - npm run lh -- --perf --seo --a11y --bp https://blog-staging.vatz88.in/
